query($id: AccountID!) {
  account(id: $id) {
    id
    sequenceNumber
    thresholds {
      low
      medium
      high
      masterWeight
    }
    ledger {
      seq
    }
    balances {
      asset {
        id
        issuer {
          id
        }
        code
      }
      balance
      limit
      authorized
    }
    signers {
      signer
      weight
    }
    data {
      name
      value
    }
  }
}
