query($id: AccountID!) {
  account(id: $id) {
    id
    sequenceNumber
    thresholds {
      low
      medium
      high
      masterWeight
    }
    flags {
      authRequired
      authRevokable
      authImmutable
    }
    ledger {
      seq
    }
    trustLines {
      asset {
        native
        issuer {
          id
        }
        code
      }
      balance
      limit
      authorized
    }
    signers {
      signer {
        id
      }
      weight
    }
    data {
      name
      value
    }
  }
}
