query($id: AccountID!) {
  operations(
    account: $id
    first: 10
    offset: 0
  ) {
    kind

    ... on PaymentOperation {
      source
      destination
      asset {
        code
      }
      amount
    }

    ... on SetOptionsOperation {
      clearFlags
      homeDomain
      masterWeight
    }
  }
}
