query($id: AccountID!) {
  accountOperations(
    account: $id
    kinds: [payment]
    filters: {
      payment: {
        asset: {
          code: "XLM"
        }
      }
    }
    first: 10
    offset: 0
  ) {
    kind

    ... on PaymentOperation {
      source
      destination
      dateTime
      asset {
        code
      }
      amount
    }
  }
}
